---
.travis.yml:
  docker_sets:
    - set: centos6-64
    - set: centos7-64
    - set: centos8-64
    - set: debian8-64
    - set: debian9-64
    - set: debian10-64
    - set: ubuntu1604-64
    - set: ubuntu1804-64
  secure: "SDpX6jzritODonEQBqy9g0NbOmk2a9dBfAtZLrvHwM8BTpM2W0Y1daqzIbpzxFiqlNX+6r2GSq9SV70N0A9Ko/uPV9aG/XZx7MsBR9DNVjgqjJSl7+aF88VJfRpOv4PAyTM33JMx91nLFxM/ql61YX+2DXGXrhUkBsMZcdBgQnk="
spec/spec_helper.rb:
  mock_with: ':rspec'
